name: Linter

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run black check
      run: poetry run black --check .
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run flake8 check
      run: poetry run flake8 --count .
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run mypy check
      run: poetry run mypy .
  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run isort check
      run: poetry run isort * -c
  autoflake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run isort check
      run: >
        poetry run autoflake -c -i -r --in-place --remove-all-unused-imports --remove-duplicate-keys --remove-unused-variable .
  Linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        echo ${{ github.base_ref }}
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: >
        pylint --disable=all
        --ignore-paths=alembic
        --max-line-length=240
        --enable=unused-import,singleton-comparison,unidiomatic-typecheck,consider-using-enumerate,\
        consider-iterating-dictionary,line-too-long,too-many-lines,trailing-whitespace,missing-final-newline,\
        bad-whitespace,bad-continuation,wrong-import-order,ungrouped-imports,wrong-import-position,return-in-init,\
        function-redefined,not-in-loop,return-outside-function,undefined-variable,no-staticmethod-decorator,bad-indentation,\
        wildcard-import,unused-variable,unused-argument
        $(git ls-files '*.py')
